### ISSUE TITLE
No fence is allowed? pgsqldA_stop_0 on <hostname> 'invalid parameter'

### ISSUE THREAD

**Issue by amoschb** [dalibo/PAF#114]
Hi,

I'm following this guide (https://dalibo.github.io/PAF/Quick_Start-CentOS-7.html) to create a 3 nodes cluster of PostgreSQL with Pacemaker/Corosync

**=======The content of script:======**

~~~
pcs cluster cib pgsql_cfg
pcs -f pgsql_cfg property set stonith-enabled="false"                    
pcs -f pgsql_cfg resource defaults resource-stickiness="INFINITY"
pcs -f pgsql_cfg resource defaults migration-threshold="5"

pcs -f pgsql_cfg resource create pgsqldA ocf:heartbeat:pgsqlms \
        bindir=/usr/pgsql-9.6/bin pgdata=/var/lib/pgsql/9.6/data \
        op start timeout=60s \
        op stop  timeout=60s \
        op promote timeout=30s \
        op demote  timeout=120s \
        op monitor interval=15s timeout=10s role="Master" \
        op monitor interval=16s timeout=10s role="Slave" \
        op notify timeout=60s

pcs -f pgsql-cfg resource master pgsql-ha pgsqldA \
        master-max=1 master-node-max=1 \
        clone-max=3 clone-node-max=1 notify=true

pcs -f pgsql-cfg resource create pgsql-master-ip ocf:heartbeat:IPaddr2 \
        ip=172.31.107.252 cidr_netmask=24 op monitor interval=10s

pcs -f pgsql_cfg constraint colocation add pgsql-master-ip with master pgsql-ha INFINITY
pcs -f pgsql_cfg constraint order promote pgsql-ha then start pgsql-master-ip symmetrical=false kind=Mandatory
pcs -f pgsql_cfg constraint order demote  pgsql-ha then stop  pgsql-master-ip symmetrical=false kind=Mandatory

pcs cluster cib-push pgsql_cfg
~~~

**=====The result of execution of script=====**

~~~
sudo ./pgsql_cluster_setup.sh 
Error: unable to create resource/fence device 'pgsqld', 'pgsqld' already exists on this system
Error: Unable to find resource or group with id pgsqld
Error: Resource 'pgsql-master-ip' does not exist
Error: Resource 'pgsql-ha' does not exist
Error: Resource 'pgsql-ha' does not exist
CIB updated
~~~

**======sudo pcs status output========**

~~~
Full list of resources:

 ClusterIP	(ocf::heartbeat:IPaddr2):	Started node1
 pgsqld	(ocf::heartbeat:pgsqlms):	FAILED (blocked)[ node3 node2 node1]

Failed Actions:
* pgsqld_stop_0 on node2 'invalid parameter' (2): call=24, status=complete, exitreason='none',
    last-rc-change='Tue Aug  8 16:42:33 2017', queued=0ms, exec=141ms
* pgsqld_stop_0 on node3 'invalid parameter' (2): call=16, status=complete, exitreason='none',
    last-rc-change='Tue Aug  8 16:42:33 2017', queued=0ms, exec=135ms
* pgsqld_stop_0 on node1 'invalid parameter' (2): call=17, status=complete, exitreason='none',
    last-rc-change='Tue Aug  8 16:42:33 2017', queued=0ms, exec=140ms
~~~

Thanks in advance!

**Comment by ioguix** [comment]
Hi,

The error message says the `pgsqld` resource already exists. According to this output, it seems you probably tried to run your script multiple times without cleaning up the cluster between each run.

Building the cluster without fencing is not advised. There a bunch of situations where your cluster will be stuck because of a failing stop action or a non-responsible node.

If you want to keep the stonith part for later, at least, setup a watchdog so each node can fence itself on stop failure. It has been documented in the fencing page: http://dalibo.github.io/PAF/fencing.html#using-a-watchdog-device

Back to your error, I suspect something is going wrong in your PostgreSQL setup. Make sure your `postgresql.conf` and `recovery.conf.pcmk` follow the requirements **on each node**.

Now your cluster failed, before starting it again, you might want to make sure your PostgreSQL instances are still in a position where one master is shutdown on a node and two standby are shutdown (and ready to SR on start) on other nodes.
