### ISSUE TITLE
Stats_temp_directory not existing after server restart under Debian 8

### ISSUE THREAD

**Issue by mrimbault** [dalibo/PAF#17]
On a Debian 8 box, a PostgreSQL instance created using Debian packaged tool `pg_createcluster` (like the instance automatically created at the package installation) is configured with the following parameter [1] :

```
stats_temp_directory = '/var/run/postgresql/9.5-main.pg_stat_tmp'
```

The problem is that `/var/run` is a symlink to `/run`, which is a `tmpfs`.
So if the box reboots, the directory does not exist anymore.
An instance managed by Debian utilities like `pg_ctlcluster` recreates it at startup, but PAF uses PostgreSQL's `pg_ctl` command, not Debian specific tools, so the PostgreSQL instance can not be started again until this directory has been manually created.

I see no easy workaround here, so maybe we should add on PAF's prerequisites that the directory configured for `stats_temp_directory` should not be _under_ a `tmpfs` (but still it can be the mount point of a `tmpfs`).
If so, we also need to fix the Debian 8 Quick start to adapt this parameter.

[1]: Cf. the related [Debian bug report](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=739276) that leads to the inclusion of this feature on Debian packaged PostgreSQL.

**Comment by sebpcspkr** [comment]
Hello,

I thnik another way could be to act as pg_ctlcluster : recreate the directory if needed just before calling pg_ctl .
If it already exists, there's no impact.
Or did I miss something  else?

**Comment by ioguix** [comment]
Hi,

I'm not that enthusiast to add some specific OS related code blocs into PAF because of debatable packaging choices. In my opinion, this should stay outside of PAF.

Create this folder in a new system service file, in a rc.d, or whatever solution suit you. The only important point is that this service is ran BEFORE the Pacemaker one.

Oh wait, you could even do it using the `anything` resource agent, a small shell script that will be called by this resource and an order constraint in the pacemaker conf. A bit overkill, but doable :)

Anyway, my vote goes to a system side solution or in the Pacemaker conf, but not in the PAF code itself.

**Comment by ioguix** [comment]
Oh sorry, you can not use the `anything` resource agent, this is designed for daemon only processes.

**Comment by sebpcspkr** [comment]
Hi,
I understand you don't want  to add some specific OS related.
On the other side, the PAF's prerequisites "that the directory configured for stats_temp_directory should not be under a tmpfs" doesn't seem a good deal to me, I prefer the approach that says it must be created BEFORE the Pacemaker service runs (but that's where your vote goes to :) )

Bye

**Comment by ioguix** [comment]
Hi,

Yes, you are right, we should not have such a prerequisites neither. So we are agree here :)

We'll keep this issue open until we update the Debian 8 Quick start guide. 

Cheers,

**Comment by ioguix** [comment]
Hi,

We messed with this with @sebpcspkr yesterday to create a unit file which takes care of this folder on system boot.

However, when getting back on this today to publish it, I found that this was actually already handled by the `postgresql-common` package in a better way since its version 159: the `/var/run/postgresql` folder is created by `systemd-tmpfiles` as a temp directory thanks to the `/usr/lib/tmpfiles.d/postgresql.conf` file. 

Moreover, I believe this action is executed during the sysinit target using the `systemd-tmpfiles-setup.service`. So this folder must exists when Pacemaker starts your PostgreSQL instance.

@mrimbault , could you investigate a bit to understand how you end-up with such issue? How did you install PostgreSQL on your Debian 8?

**Comment by mrimbault** [comment]
I don't think I did anything special during the install process (classic PostgreSQL installation using the PGDG repository).
I confirm that the `/var/run/postgresql` is not an issue by itself, the one that caused my problem was the `/var/run/postgresql/9.5-main.pg_stat_tmp` sub-directory, as configured by default when using PostgreSQL 9.5 packaging on Debian 8 (`stats_temp_directory` parameter).
I'll try to have a more detailed look at this point to confirm that it is still an issue with a default installation, and which PostgreSQL versions are affected.

**Comment by ioguix** [comment]
Oh, OK, understood my problem with my tests. Sorry that was on my side.

So the solution I found is to create a conf file to extend the tmpfiles one for the postgresql package:

```
cat <<EOF > /etc/tmpfiles.d/postgresql-part.conf 
# Directory for PostgreSQL temp stat files
d /var/run/postgresql/9.5-main.pg_stat_tmp 0700 postgres postgres - -
EOF
```
