### ISSUE TITLE
MAster node doesnt start after fail.

### ISSUE THREAD

**Issue by alimumcu1077** [dalibo/PAF#46]
I have create 3 node postgesql cluster .(srv1(master),srv2(slave),srv3(slave) for testing.
I disable master node(srv1) network and then fence device power of master node . And then second node (srv2) become master  so It worked properly up to this point.
After i open my old master node srv1 when i try to start srv1 it has gt error and it have power of autamatically.( i run "pcs  cluster start srv1" command.)

To make srv1 node  as a master again what can i do. 
I have used postgresql 9.4 and i used yours setup(http://dalibo.github.io/PAF/Quick_Start-CentOS-7.html)

Best Regards.

**Comment by alimumcu1077** [comment]
**[root@srv1 ~]# pcs status**
Cluster name: cluster_pgsql
Last updated: Wed Oct 19 01:11:54 2016          Last change: Wed Oct 19 01:11:09 2016 by root via crm_attribute on srv2
Stack: corosync
Current DC: srv3 (version 1.1.13-10.el7_2.4-44eb2dd) - partition with quorum
3 nodes and 7 resources configured

Online: [ srv1 srv2 srv3 ]

Full list of resources:

 fence_vm_srv1  (stonith:fence_vmware_soap):    Started srv2
 fence_vm_srv2  (stonith:fence_vmware_soap):    Started srv1
 fence_vm_srv3  (stonith:fence_vmware_soap):    Started srv1
 Master/Slave Set: pgsql-ha [pgsqld]
     Masters: [ srv2 ]
     Slaves: [ srv3 ]
     Stopped: [ srv1 ]
 pgsql-master-ip        (ocf::heartbeat:IPaddr2):       Started srv2

Failed Actions:
* pgsqld_start_0 on srv1 'unknown error' (1): call=25, status=complete, exitreason='none',
    last-rc-change='Wed Oct 19 01:10:42 2016', queued=0ms, exec=1138ms


PCSD Status:
  srv1: Online
  srv2: Online
  srv3: Online

Daemon Status:
  corosync: active/disabled
  pacemaker: active/disabled
  pcsd: active/enabled

**Comment by ioguix** [comment]
Hi,

You get this because your old master wasn't shutdown properly, obviously because of the node fencing.

When Pacemaker tries to start it again, PAF check if the instance is clean and raise an error because it find it has crashed.

Default behavior of Pacemaker is to block or fence a resource when it fails to start.

If you want to get your old master back to the cluster as a slave, you will have to rebuild it to make it clean before starting Pacemaker on this node again. This is the simple way. If you have a good understanding of PostgreSQL, you can use rsync or pg_rewind to get it back faster.

There's some documentation about this there: http://dalibo.github.io/PAF/administration.html#rebuild-the-failed-postgresql-instance
