### ISSUE TITLE
Create cluster with one node, then after some time add another

### ISSUE THREAD

**Issue by alexaht** [dalibo/PAF#79]
Hello, 

Trying to write universal script to create cluster with only one node, with possibility to add new nodes later. After creating postgres resource, it becomes slave... How can i made him force promote to master on cluster resource creation?

**Comment by ioguix** [comment]
Hello,

What version of PAF are you using?

It would be interesting to understand why it doesn't promote, if it comes from Pacemaker of the RA itself.

Anyway, if this comes from the RA, you can try to set its master score using `crm_master -r <rsc_name> -N <node> -v 1001` (did not check, you might need to adjust), then Pacemaker should probably promote it.

If Pacemaker refuse to promote it because the resource is alone or something else, we would need to have a better understanding of this issue.

**Comment by ioguix** [comment]
You are welcome!
